# Generated by Django 4.2.2 on 2023-08-30 19:43

from django.db import migrations, models
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(verbose_name="Nome")),
                ("document", models.JSONField(verbose_name="Documento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AWAITING", "Awaiting"),
                            ("APPROVED", "Approved"),
                            ("REFUSED", "Refused"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposal_name",
                    models.TextField(
                        auto_created=True,
                        default="Modelo de Proposta",
                        verbose_name="Model Name",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=functools.partial(
                            dict,
                            *(),
                            **{"CPF": "descrição...", "IDADE": "descrição..."}
                        ),
                        verbose_name="Conteúdo da Proposta",
                    ),
                ),
            ],
        ),
    ]
